# Generated by Django 4.2.2 on 2023-06-28 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subject',
            new_name='Topic',
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'topic', 'verbose_name_plural': 'topics'},
        ),
    ]
