# Generated by Django 4.2.2 on 2023-06-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_subtopic'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subtopic',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
