# Generated by Django 4.2.2 on 2023-07-04 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subtopic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='forum.subtopic'),
        ),
    ]
