# Generated by Django 4.2.2 on 2023-07-06 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_alter_post_subtopic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('created',), 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
